// Run code from SubscriberClass01
System.debug('\n\nEXECUTING SubscriberClass01\n\n');
SubscriberClass01 sc01 = new SubscriberClass01();

// Run code from SubscriberClass02
System.debug('\n\nEXECUTING SubscriberClass02\n\n');
SubscriberClass02 sc02 = new SubscriberClass02();

// Run code from SubscriberClass03
System.debug('\n\nEXECUTING SubscriberClass03\n\n');
SubscriberClass03 sc03 = new SubscriberClass03();